name: autopartes_mall
description: autopartes_mall

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^2.2.1
  url_launcher: ^6.0.12
  scrollable_positioned_list: ^0.1.7
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: 0.8.0
  cloud_firestore: 2.5.3
  flutter_stripe: 2.0.0
  cloud_functions: 3.0.4
  firebase_storage:
  image_picker: 0.7.1
  progress_dialog: ^1.2.2
  intl: ^0.17.0
#  firebase_auth:
  dropdownfield: ^1.0.3
  excel: ^1.1.5
#  flutter_bloc: ^8.0.0
#  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0


flutter_icons:
  image_path: "assets/img/logo_am.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/img/
   - assets/img/profile-screen-bg.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 600
